### ISSUE TITLE
GetData endpoint should always return 200 OK

### ISSUE THREAD

**Issue by abjerner** [skybrud/Skybrud.Umbraco.Spa#12]
To have a more API-like behavior, @skybrud/frontenders would like the GetData endpoint to always return 200 OK, and then indicate the desired HTTP status code in the response body instead.

@skybrud/frontenders any preference for the JSON structure? Back in the day we had a `meta` object with a `status` property. Would this suffice?

![image](https://user-images.githubusercontent.com/3634580/123101841-bb423b80-d434-11eb-95b5-f1a201104b40.png)

**Comment by saulhardman** [comment]
Hej @abjerner, sorry for the delay – Empirical has had me pretty swamped. Taking a look at this now :+1:

**Comment by saulhardman** [comment]
`meta.code` sounds reasonable to me 👌

**Comment by abjerner** [comment]
@saulhardman great 😄 

How do we handle 500 errors? Just like now?

**Comment by saulhardman** [comment]
> @saulhardman great 😄
> 
> How do we handle 500 errors? Just like now?

As we do now, yes.

**Comment by abjerner** [comment]
@saulhardman I've now pushed a new release that should change the status code behavior (which is now default):

https://github.com/skybrud/Skybrud.Umbraco.Spa/releases/tag/v3.0.0-beta013

Any client projects where we need this then needs to be updated with this version. The backender of each project should be able to help you with that 😉
