### ISSUE TITLE
Cached 404 page requests return statuscode 200

### ISSUE THREAD

**Issue by jemayn** [skybrud/Skybrud.Umbraco.Spa#13]
# The issue

When you request the GetData api for a route that Umbraco doesn't know about we return the 404 page, and return http statuscode 404 - along with the full json response for site, nav, etc.

However it seems the 404 statuscode is only on uncached attempts, so if you refresh the next few attempts will return status code 200 instead until the cache expires.

# Reproduction steps:
_This is probably the same on other sites, but know for sure it can be reproduced on the following commit:_
- Clone and checkout this commit https://github.com/limbo-works/Empirical-Website-Shop-Umbraco-8/commit/48b4943d3859a2a61911980ff2522f5542482a52
- Get the site running
- Build in Release mode (caching is automatically disabled in debug)
- Request GetData for a nonexistant url, fx: 7984em.jmayn/umbraco/api/spa/GetData?url=/miaow/
- First request returns 404, subsequent requests return 200

**Comment by abjerner** [comment]
Thanks Jesper 👍 

This should now be fixed: https://github.com/skybrud/Skybrud.Umbraco.Spa/releases/tag/v3.0.0-beta013
