### ISSUE TITLE
ContentChangeGuid on publication

### ISSUE THREAD

**Issue by rpjengaard** [skybrud/Skybrud.Umbraco.Spa#2]
Vi mangler at flytte denne over i SPA pakken

`private void ContentService_Published(Umbraco.Core.Publishing.IPublishingStrategy sender, Umbraco.Core.Events.PublishEventArgs<IContent> e)
        {
            //Bruges til at udføre custom-handlinger når et dokument er udgivet
            
            Startup.ContentChangesGuid = Guid.NewGuid();    //clear localstorage on change
        }`

**Comment by abjerner** [comment]
Dette er tilføjet i 147d8f087d0c78062caa085ca5f01674fb6f36ee

Jeg har lavet sådan, så der nu er en `SpaCacheService`, som man kan kalde for at få cachen tømt. Så kan vi nemlig også referere til den andre steder i koden:

https://github.com/skybrud/Skybrud.Umbraco.Spa/blob/master/src/Skybrud.Umbraco.Spa/Services/SpaCacheService.cs

Og så en `SpaCacheComponent`, der lytter på de forskellige events (ved ikke lige pt. om der er flere vi bør lytte på), og så via dependency injection kalder ovenstående service for at tømme cachen:

https://github.com/skybrud/Skybrud.Umbraco.Spa/blob/master/src/Skybrud.Umbraco.Spa/Components/SpaCacheComponent.cs
