### ISSUE TITLE
Flytte spa extensions over

### ISSUE THREAD

**Issue by rpjengaard** [skybrud/Skybrud.Umbraco.Spa#3]
https://bitbucket.org/skybrud/spa-2-boilerplate/src/ac7f4d0babc03bab4870c864d7820bb6e0279d0c/dev/code/Extensions/SpaExtensions.cs#lines-50

Se sidste 3 extensions skal flyttes. De andre er løsningsspecifikke

**Comment by abjerner** [comment]
`IsPreviewUrl` og `GetPreviewId` findes allerede i SPA-pakken, så de er på plads.

`IsExistingNode` har jeg ikke set før, så jeg ved ikke hvor den er brugt. Jeg tænker også at opslaget må kunne laves pænere i Umbraco 8, så lad os evt. gemme den til senere.
